# Generated by Django 3.2.5 on 2021-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('tasks', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
