# Generated by Django 3.2.5 on 2021-07-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do',
            old_name='created_on',
            new_name='time_created',
        ),
    ]
