# Generated by Django 3.2.4 on 2021-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_to_do_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
